import type { Race } from '../model/db/raceDbModel';

const mockRacesData: Race[] = [
    {
        id: 1,
        name: 'Course du Alix affamé',
        raid_id: 1,
        date: '15 juin 2026',
        type: 'rando/loisir',
        age_range: '0-99 ans',
        distance: 15,
        price: 12,
        description: 'Une course de randonnée accessible à tous les niveaux.',
        image_url: undefined,
    },
    {
        id: 2,
        name: 'Trail Intensif',
        raid_id: 1,
        date: '16 juin 2026',
        type: 'compétition',
        age_range: '18-65 ans',
        distance: 42,
        price: 25,
        description: 'Trail compétitif avec dénivelé significatif.',
        image_url: undefined,
    },
    {
        id: 3,
        name: 'Exploration Extrême',
        raid_id: 1,
        date: '22 juin 2026',
        type: 'extrême',
        age_range: '16+ ans',
        distance: 85,
        price: 45,
        description: 'Course d\'aventure extrême en forêt noire.',
        image_url: undefined,
    },
    {
        id: 4,
        name: 'Rando Montagne Familiale',
        raid_id: 3,
        date: '5 juillet 2026',
        type: 'rando/loisir',
        age_range: '6-99 ans',
        distance: 10,
        price: 15,
        description: 'Randonnée en montagne adaptée aux familles.',
        image_url: undefined,
    },
    {
        id: 5,
        name: 'Nocturne Challenge',
        raid_id: 4,
        date: '12 juillet 2026',
        type: 'compétition',
        age_range: '18-99 ans',
        distance: 21,
        price: 30,
        description: 'Course de nuit avec équipement spécialisé.',
        image_url: undefined,
    },
    {
        id: 6,
        name: 'Littoral Explorer',
        raid_id: 5,
        date: '20 juillet 2026',
        type: 'rando/loisir',
        age_range: '0-99 ans',
        distance: 12,
        price: 18,
        description: 'Exploration des côtes et plages.',
        image_url: undefined,
    },
    {
        id: 7,
        name: 'Désert Hardcore',
        raid_id: 6,
        date: '28 juillet 2026',
        type: 'extrême',
        age_range: '16+ ans',
        distance: 100,
        price: 50,
        description: 'Épreuve extrême en conditions désertiques.',
        image_url: undefined,
    },
    {
        id: 8,
        name: 'Urban Race',
        raid_id: 7,
        date: '5 août 2026',
        type: 'compétition',
        age_range: '12-99 ans',
        distance: 10,
        price: 20,
        description: 'Course urbaine dynamique et fun.',
        image_url: undefined,
    },
    {
        id: 9,
        name: 'Découverte des Lacs',
        raid_id: 8,
        date: '15 août 2026',
        type: 'rando/loisir',
        age_range: '0-99 ans',
        distance: 8,
        price: 14,
        description: 'Rando autour des lacs alpins.',
        image_url: undefined,
    },
    {
        id: 10,
        name: 'Extrême Mountain',
        raid_id: 9,
        date: '25 août 2026',
        type: 'extrême',
        age_range: '16+ ans',
        distance: 120,
        price: 55,
        description: 'Épreuve alpestre d\'extrême difficulté.',
        image_url: undefined,
    },
];

export const getListOfRacesByRaidId = (raidId: number) => {
    return mockRacesData.filter(race => race.raid_id === raidId);
};