import type { Race } from '../model/db/raceDbModel';

const mockRacesData: Race[] = [
    {
        id: 1,
        race_id: 101,
        raid_id: 1,
        date: '15 juin 2026',
        race_time_start: '08:00',
        race_time_end: '12:30',
        type: 'rando/loisir',
        age_range: '0-99 ans',
        difficulty: 'facile',
        distance: 15,
        price: 12,
        max_participants: 50,
        registered_participants: 38,
        team_members: 2,
        description: 'Une course de randonnée accessible à tous les niveaux.',
        image_url: undefined,
    },
    {
        id: 2,
        race_id: 102,
        raid_id: 1,
        date: '16 juin 2026',
        race_time_start: '07:00',
        race_time_end: '14:15',
        type: 'compétition',
        age_range: '18-65 ans',
        difficulty: 'difficile',
        distance: 42,
        price: 25,
        max_participants: 60,
        registered_participants: 52,
        team_members: 3,
        description: 'Trail compétitif avec dénivelé significatif.',
        image_url: undefined,
    },
    {
        id: 3,
        race_id: 103,
        raid_id: 1,
        date: '22 juin 2026',
        race_time_start: '06:00',
        race_time_end: '18:00',
        type: 'extrême',
        age_range: '16+ ans',
        difficulty: 'difficile',
        distance: 85,
        price: 45,
        max_participants: 40,
        registered_participants: 35,
        team_members: 4,
        description: 'Course d\'aventure extrême en forêt noire.',
        image_url: undefined,
    },
    {
        id: 4,
        race_id: 104,
        raid_id: 3,
        date: '5 juillet 2026',
        race_time_start: '09:00',
        race_time_end: '13:30',
        type: 'rando/loisir',
        age_range: '6-99 ans',
        difficulty: 'facile',
        distance: 10,
        price: 15,
        max_participants: 80,
        registered_participants: 64,
        team_members: 3,
        description: 'Randonnée en montagne adaptée aux familles.',
        image_url: undefined,
    },
    {
        id: 5,
        race_id: 105,
        raid_id: 4,
        date: '12 juillet 2026',
        race_time_start: '20:00',
        race_time_end: '23:45',
        type: 'compétition',
        age_range: '18-99 ans',
        difficulty: 'moyen',
        distance: 21,
        price: 30,
        max_participants: 55,
        registered_participants: 48,
        team_members: 2,
        description: 'Course de nuit avec équipement spécialisé.',
        image_url: undefined,
    },
    {
        id: 6,
        race_id: 106,
        raid_id: 5,
        date: '20 juillet 2026',
        race_time_start: '10:00',
        race_time_end: '14:00',
        type: 'rando/loisir',
        age_range: '0-99 ans',
        difficulty: 'facile',
        distance: 12,
        price: 18,
        max_participants: 70,
        registered_participants: 56,
        team_members: 2,
        description: 'Exploration des côtes et plages.',
        image_url: undefined,
    },
    {
        id: 7,
        race_id: 107,
        raid_id: 6,
        date: '28 juillet 2026',
        race_time_start: '05:30',
        race_time_end: '19:30',
        type: 'extrême',
        age_range: '16+ ans',
        difficulty: 'difficile',
        distance: 100,
        price: 50,
        max_participants: 35,
        registered_participants: 28,
        team_members: 4,
        description: 'Épreuve extrême en conditions désertiques.',
        image_url: undefined,
    },
    {
        id: 8,
        race_id: 108,
        raid_id: 7,
        date: '5 août 2026',
        race_time_start: '18:00',
        race_time_end: '20:30',
        type: 'compétition',
        age_range: '12-99 ans',
        difficulty: 'moyen',
        distance: 10,
        price: 20,
        max_participants: 90,
        registered_participants: 71,
        team_members: 2,
        description: 'Course urbaine dynamique et fun.',
        image_url: undefined,
    },
    {
        id: 9,
        race_id: 109,
        raid_id: 8,
        date: '15 août 2026',
        race_time_start: '09:30',
        race_time_end: '13:00',
        type: 'rando/loisir',
        age_range: '0-99 ans',
        difficulty: 'facile',
        distance: 8,
        price: 14,
        max_participants: 100,
        registered_participants: 82,
        team_members: 2,
        description: 'Rando autour des lacs alpins.',
        image_url: undefined,
    },
    {
        id: 10,
        race_id: 110,
        raid_id: 9,
        date: '25 août 2026',
        race_time_start: '04:00',
        race_time_end: '20:00',
        type: 'extrême',
        age_range: '16+ ans',
        difficulty: 'difficile',
        distance: 120,
        price: 55,
        max_participants: 30,
        registered_participants: 24,
        team_members: 4,
        description: 'Épreuve alpestre d\'extrême difficulté.',
        image_url: undefined,
    },
];

export const getListOfRacesByRaidId = (raidId: number) => {
    return mockRacesData.filter(race => race.raid_id === raidId);
};